### ISSUE TITLE
Possible to set parent to multiple blocks in builder at one time?

### ISSUE THREAD

**Issue by PhaserlockBren** [jjburton/cgmTools#107]
I was wondering if its possible to add the ability to parent multiple rigblocks to "active" at one time in builder?
for instance - im working with toes - I unparented and duplicated the blocks - moved them to the rear foot and re-parented...setting parent seems to only work one block at a time...

Im sure you've considered it - and likely a really good reason why you cant...but had ta ask

**Comment by jjburton** [comment]
Yup.  

- Select multiple blocks in the picker
- Top menu > Block> Parent
