### ISSUE TITLE
MRS_Scenes - view doesnt expand to show all details about the shots in the file

### ISSUE THREAD

**Issue by PhaserlockBren** [jjburton/cgmTools#111]
![Scenes_Image](https://user-images.githubusercontent.com/68934362/90826755-a2db2f00-e300-11ea-8cc2-419aa2f5f2d4.png)
I should be able to see the names of the shots identified in the file if I expand my window vertically.

the first portion of the names are cut off

**Comment by jjburton** [comment]
On current scene to do list
