### ISSUE TITLE
Scenes batch export file naming

### ISSUE THREAD

**Issue by PhaserlockBren** [jjburton/cgmTools#113]
I added these files to the batch export:Dinosaurs - TRex - ANIM_Alerted - None - TRex_ANIM_Alerted_BLOCKING.mb
Dinosaurs - TRex - ANIM_Attacks - None - TRex_ANIM_Attacks_BLOCKING.mb
Dinosaurs - TRex - ANIM_Death - None - TRex_ANIM_Death_BLOCKING.mb
Dinosaurs - TRex - ANIM_Desires - None - TRex_ANIM_Desires_BLOCKING.mb
Dinosaurs - TRex - ANIM_Idle - None - TRex_ANIM_Idle_BLOCKING.mb
Dinosaurs - TRex - ANIM_Strafe_melee - None - TRex_ANIM_Strafe_melee_BLOCKING.mb
Dinosaurs - TRex - ANIM_TakeDamage - None - TRex_ANIM_TakeDamage_BLOCKING.mb

**Comment by PhaserlockBren** [comment]
The exported files had "_BLOCKING" stripped from the exported naming convention.

**Comment by dbokser** [comment]
this is the intended functionality. The exported filename will be taken based on the assetname, subtype, and variation as to prevent a bunch of extraneous versioning in the engine and for it to easily update rig and animation files with newer versions from Maya.

So, if you have an asset name called TRex, and an animation named ANIM_Death, it will export anything from there as Dinosaurs/TRex/animation/ANIM_Death/TRex_ANIM_Death.fbx

If you include variant in the animation subtype in your MRSProject settings, you could create a variation under the animation called BLOCKING and that will export with the name you have there - Dinosaurs/TRex/animation/ANIM_Death/TRex_ANIM_Death_BLOCKING.fbx

![image](https://user-images.githubusercontent.com/2582947/92164117-6debd380-edfa-11ea-8f8b-66753afe0973.png)

**Comment by PhaserlockBren** [comment]
AAhh – Excellent, Thanks! Im sure Josh told me that and I missed it 😊  Thanks for the clarification!  Sent from Mail for Windows 10 From: David BokserSent: Thursday, September 3, 2020 3:32 PMTo: jjburton/cgmToolsCc: PhaserlockBren; AuthorSubject: Re: [jjburton/cgmTools] Scenes batch export file naming (#113) this is the intended functionality. The exported filename will be taken based on the assetname, subtype, and variation as to prevent a bunch of extraneous versioning in the engine and for it to easily update rig and animation files with newer versions from Maya.So, if you have an asset name called TRex, and an animation named ANIM_Death, it will export anything from there as Dinosaurs/TRex/animation/ANIM_Death/TRex_ANIM_Death.fbxIf you include variant in the animation subtype in your MRSProject settings, you could create a variation under the animation called BLOCKING and that will export with the name you have there - Dinosaurs/TRex/animation/ANIM_Death/TRex_ANIM_Death_BLOCKING.fbx—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by PhaserlockBren** [comment]
I do have a followup pquestion. When I select the “ Variant” checkbox and save / push to scene, the files that were displaying in the “ versions” window no longer display. Additionally, I previously had saved the files with the “ blocking “ naming in the file, they don’t display either. I originally didn’t create them within scene, but rather as a different version while in Maya- I had expected that they would show up in Scene, which they did prior to selecting the “Variant” checkbox. Is it expected that they’d display as a variation in scene? Wondering why no files display at all with “ variant” selected. ( without “Variant”) (With “ Variant”) Sent from Mail for Windows 10 From: David BokserSent: Thursday, September 3, 2020 3:32 PMTo: jjburton/cgmToolsCc: PhaserlockBren; AuthorSubject: Re: [jjburton/cgmTools] Scenes batch export file naming (#113) this is the intended functionality. The exported filename will be taken based on the assetname, subtype, and variation as to prevent a bunch of extraneous versioning in the engine and for it to easily update rig and animation files with newer versions from Maya.So, if you have an asset name called TRex, and an animation named ANIM_Death, it will export anything from there as Dinosaurs/TRex/animation/ANIM_Death/TRex_ANIM_Death.fbxIf you include variant in the animation subtype in your MRSProject settings, you could create a variation under the animation called BLOCKING and that will export with the name you have there - Dinosaurs/TRex/animation/ANIM_Death/TRex_ANIM_Death_BLOCKING.fbx—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dbokser** [comment]
when you set up the variant checkbox, the variation column should be shown in scene. Create a New Variation in scene on the bottom of the column called BLOCKING, and then move the files you saved over previously from: TRex/animation/ANIM_Death to TRex/animation/ANIM_Death/BLOCKING
and if they're still not showing up then in the scene top menu select 

Options - Show all files 

as Scene hides any files that are not following the naming conventions by default. If you open one of your files and click Save New Version, it will name the next version according to the naming convention it's expecting (TRex_ANIM_Death_BLOCKING_01.mb, TRex_ANIM_Death_BLOCKING_02.mb, etc)
