### ISSUE TITLE
Mirror Verify Thumb Block shape handle error

### ISSUE THREAD

**Issue by benngarnish** [jjburton/cgmTools#12]
https://www.dropbox.com/s/qbrn3mluoswjjyh/thumbOut.PNG?dl=0

When I mirror the thumb block I get the above error.
I can fix it by bringing this side back to template and then pushing the right side again which seems to pull the handles back into place.

**Comment by jjburton** [comment]
Push/pull the mirror after the verify. We'll be retooling blockDat load/store with the rig config/profile milestone
