### ISSUE TITLE
Shape Form mirror error

### ISSUE THREAD

**Issue by benngarnish** [jjburton/cgmTools#130]
Mirror will run and build the opposite arm. However, the amount of curves isn't the same even tho the num SubShapers is the same.

In this case the left arm was built from the right side.

![shapeForm_mirrorError](https://user-images.githubusercontent.com/1122587/97555445-0bfdb380-19d0-11eb-8203-95189efcd9e8.png)

**Comment by jjburton** [comment]
@benngarnish | pretty sure this is resolved on the private testing build. I'll push today.

**Comment by benngarnish** [comment]
@jjburton 
Can we close this now?
