### ISSUE TITLE
Builder | Send to maya py update

### ISSUE THREAD

**Issue by jjburton** [jjburton/cgmTools#135]
- [x] UI to pick what options for build with frame work to add more
- [x] Send from scene
- [ ] Close process on completion

-Moving generator to builder for easier access to optionVars
-

**Comment by jjburton** [comment]
### Working through it

- Used Post build ui as a base to make new one
- Pulled batch process call to Builder to get access to option vars here easier
-

**Comment by benngarnish** [comment]
This complete?
