### ISSUE TITLE
cgmSimChain error

### ISSUE THREAD

**Issue by salmonskin01** [jjburton/cgmTools#151]
Hi there,

When I try to open cgmSimChain, I get this error. Any idea why? Thanks! 

# cgm.core.classes.GuiFactory : |__init__[cgmSimChain.ui]| >>... # 
# cgm.core.classes.GuiFactory : |setup_baseVariables[cgmSimChain.ui]| >>... # 
# cgm.core.tools.dynFKTool : |__init__[cgmSimChain.ui]| >>... # 
# cgm.core.tools.dynFKTool : args: (u'cgmSimChain_ui',) # 
# cgm.core.tools.dynFKTool : cgmSimChain - 0.05052020 # 
/// __init__   ///----------------------------------------------------------------------------------------------------
 file: D:/Documents/maya/2020/scripts\cgm\core\classes\GuiFactory.py
  Local dat...
{'_str_func': '__init__[cgmSimChain.ui]',
 'a': (),
 'err': TypeError('unbound method __init__() must be called with BaseMelWidget instance as first argument (got cgmScrollList instance instead)',),
 'kw': {},
 'self': u'cgmSimChain_ui'}
...///
/// cgmSimChain   ///----------------------------------------------------------------------------------------------------
 file: D:/Documents/maya/2020/scripts\cgm\core\tools\lib\tool_calls.py
  Local dat...
{'dynFKTool': <module 'cgm.core.tools.dynFKTool' from 'D:/Documents/maya/2020/scripts\cgm\core\tools\dynFKTool.pyc'>,
 'err': TypeError('unbound method __init__() must be called with BaseMelWidget instance as first argument (got cgmScrollList instance instead)',)}
...///
# Error: TypeError: file D:/Documents/maya/2020/scripts\cgm\core\classes\GuiFactory.py line 1763: unbound method __init__() must be called with BaseMelWidget instance as first argument (got cgmScrollList instance instead) #

**Comment by jjburton** [comment]
Looks like import order issue. Try cgm>dev> reload core. If not I'll need more info. What build of the tools, os etc. See http://mrsdocs.cgmonastery.com/support.html for reporting help.

**Comment by salmonskin01** [comment]
Reload core worked out! Thanks for ur help and fast reply.

**Comment by jjburton** [comment]
Happy to help!
