### ISSUE TITLE
Facial R&D Reference

### ISSUE THREAD

**Issue by jjburton** [jjburton/cgmTools#153]
@benngarnish , let's keep r&D here.

**Comment by benngarnish** [comment]
List of face controls:

- [ ] Jaw Open
- [ ] Jaw Close Up
- [ ] Jaw Left
- [ ] Jaw Right
- [ ] Jaw Forward
- [ ] Jaw Backward
- [ ] Mouth Close
- [ ] Mouth Sticky
- [ ] Mouth Up
- [ ] Mouth Down
- [ ] Mouth Left
- [ ] Mouth Right
- [ ] Tongue Up
- [ ] Tongue Down
- [ ] Tongue Left
- [ ] Tongue Right
- [ ] Pucker
- [ ] Funnel
- [ ] Smile Left
- [ ] Smile Right
- [ ] Frown Left
- [ ] Frown Right
- [ ] Dimpler Left
- [ ] Dimpler Right
- [ ] Sneer Left
- [ ] Sneer Right
- [ ] PullDown Left
- [ ] PullDown Right
- [ ] Presser Left
- [ ] Presser Right
- [ ] Pull Down Wide Left
- [ ] Pull Down Wide Right
- [ ] Upper Lip Roll Left
- [ ] Upper Lip Roll Right
- [ ] Eye Blink Left
- [ ] Eye Blink Right
- [ ] Eye Wide Left
- [ ] Eye Wide Right
- [ ] Eye Squint Left
- [ ] Eye Squint Right
- [ ] Eye Compress Left
- [ ] Eye Compress Right
- [ ] Eyes Look Up
- [ ] Eyes Look Down
- [ ] Eyes Look Left
- [ ] Eyes Look Right
- [ ] Nose Sneer Left
- [ ] Nose Sneer Right
- [ ] Cheek Puff Left
- [ ] Cheek Puff Right
- [ ] Cheek Suck Left
- [ ] Cheek Suck Right
- [ ] Cheek Raiser left
- [ ] Cheek Raiser Right
- [ ] Brow Inner Up Left
- [ ] Brow Inner Up Right
- [ ] Brow Inner Down Left
- [ ] Brow Inner Down Right
- [ ] Brow Outer Up Left
- [ ] Brow Outer Up Right
- [ ] Brow Outer Down Left
- [ ] Brow Outer Down Right
- [ ] Brow Squeeze

**Comment by jjburton** [comment]
@benngarnish | be good to find some reference material as well to help show what shapes users need to target? We can do our own on an asset but would be good to show some variety.

**Comment by benngarnish** [comment]
This is a recent and insane reference:
https://melindaozel.com/facs-cheat-sheet/

And another good resource: 
https://imotions.com/blog/facial-action-coding-system/

Oldy but a goody:
https://youtu.be/w_Z7YUyCEGE?t=156

**Comment by jjburton** [comment]
Some known needs:

- [ ] Joint plan | mobile
- [ ] Joint plan | current gen
- [ ] Joint plan | render/commercial

- [ ] Control plan | on face controllers, sep joystick setup that rides with face, etc.
- [ ] Control Plan | what kinds of controllers people like.

**Comment by benngarnish** [comment]
Best place to start with all of this work is mocap.
What points are being tracked across a face in order to get back the movement data?
![image](https://user-images.githubusercontent.com/1122587/101258217-f68b5000-3718-11eb-80ff-39f4b8c6d7c9.png)
![image](https://user-images.githubusercontent.com/1122587/101258237-1f134a00-3719-11eb-87ac-e5495c53cd11.png)

What can we extrapolate from this? 
The guys on God of War simplified this for their rigs:
![image](https://user-images.githubusercontent.com/1122587/101258255-3d794580-3719-11eb-8f69-9ee6a030dd79.png)

Even Jeremy Ernst a while back had started along the same lines.
![image](https://user-images.githubusercontent.com/1122587/101258274-58e45080-3719-11eb-958e-98c1a9c84816.png)

**Comment by jjburton** [comment]
I'd recommend starting with games as our base since that's the focuse of MRS and doing current gen and mobile targets. I think we can generate all the data we need from our exisiting face cage though I'll need to combine brow with the lower face for the facs block.

Would there be any reason to want only a facs brow/mouth/etc. I/e masking off regions for setup for not? Like if you had a masked person and didn't want the lower face?

**Comment by jjburton** [comment]
@benngarnish | wanna setup some open deck tasks?

- [ ] Setup new branch for facs | I'll handle
- [ ] Intial blocksetup
- [ ] Define/form state to get our cage figured out
- [ ] control plan
- [ ] tiered joint list
