### ISSUE TITLE
Scene Export Queue Entry removal

### ISSUE THREAD

**Issue by PhaserlockBren** [jjburton/cgmTools#176]
In scene Export queue - if you try to remove a highlighted entry, the entry above it will be removed instead of the highlighted entry.

**Comment by benngarnish** [comment]
Thanks for the report @PhaserlockBren 
Due to the Christmas period things will be slower to get onto.
But thanks for the report and we will get onto this as soo bad we can!!

**Comment by jjburton** [comment]
@PhaserlockBren | this is resolved on a dev branch. Will merge later this week.
