### ISSUE TITLE
can't open pipeline>scene 

### ISSUE THREAD

**Issue by broco1001** [jjburton/cgmTools#192]
error when open the pipeline scene ,
Error: TypeError: file C:/Users/andry/Documents/maya/2019/scripts\cgm\core\classes\GuiFactory.py line 2322: unbound method init() must be called with BaseMelWidget instance as first argument (got cgmScrollList instance instead)

**Comment by broco1001** [comment]
the pipeline scene work well when auto load on maya start in check mark

**Comment by jjburton** [comment]
@broco1001 | this could have been a couple of things:
- updating tools with an open window. Best to reload core after a pull and close and cgm ui's open when you need to update.
- bad pull on git

It sounds like you have it sorted.
