### ISSUE TITLE
proxy hip 

### ISSUE THREAD

**Issue by broco1001** [jjburton/cgmTools#197]
![image](https://user-images.githubusercontent.com/77574628/106435001-e091d580-64a4-11eb-9c58-7264a3f6f5e4.png)

why the hip proxy not in the same direction with spine

![image](https://user-images.githubusercontent.com/77574628/106435725-d6240b80-64a5-11eb-9616-e19fff25a5f3.png)

when I save the scene and open again the hip proxy rotate

**Comment by jjburton** [comment]
That is bizarre. 

- Maya version?
- cgm build release?
- Did you try rebuilding the proxy in scne?

**Comment by broco1001** [comment]
> That is bizarre.
> 
> * Maya version?
> * cgm build release?
> * Did you try rebuilding the proxy in scne?

I think this cause my maya 2018 not updated, I'm trying in maya 2019 it work well, I must update my maya first, thank you

**Comment by jjburton** [comment]
Yup, that'll do it. First couple of releases of a maya version should be avoided :) That said. 2018.7 is solid.
