### ISSUE TITLE
Pipeline - Project. Adding empty.txt to folders for gitHub to recognise the folder

### ISSUE THREAD

**Issue by benngarnish** [jjburton/cgmTools#198]
Unfortunatly gitHub will not identify empty folders.

Can we add, on verifying the folder drivers for export, create an empty.txt file so that gitHub will pick up the folders?

**Comment by jjburton** [comment]
Hmmm. I'm not sure I'd want that all the time. Maybe an option? Thoughts?

**Comment by jjburton** [comment]
@benngarnish | would a utility that would walk the structure and add this to any empty folders suffice ? That way it would hit custom folders you manually added

**Comment by benngarnish** [comment]
Perfect!!
