### ISSUE TITLE
Unable to use Batch Build process

### ISSUE THREAD

**Issue by afernandezpons** [jjburton/cgmTools#201]
[I  2021-02-04 11:59:40,888 | artella | __init__:current_dcc:94] > Current DCC: maya
[I  2021-02-04 11:59:40,957 | artella | plugin:register_plugin:488] > Artella Plugin: "artella-plugins-updater" registered successfully!
[I  2021-02-04 11:59:40,973 | artella | plugin:register_plugin:488] > Artella Plugin: "artella-plugins-about" registered successfully!
[I  2021-02-04 11:59:40,986 | artella | plugin:register_plugin:488] > Artella Plugin: "artella-plugins-uninstaller" registered successfully!
[I  2021-02-04 11:59:41,000 | artella | plugin:register_plugin:488] > Artella Plugin: "artella-plugins-getdependencies" registered successfully!
[I  2021-02-04 11:59:41,012 | artella | plugin:register_plugin:488] > Artella Plugin: "artella-plugins-savetocloud" registered successfully!
[W  2021-02-04 11:59:41,016 | artella | callback:initialize_callbacks:47] > Dcc maya does not provides a Callback implementation for ShutdownCallback. Skipping ...
[I  2021-02-04 11:59:41,022 | artella | client:artella_drive_connect:1137] > Connecting to Artella Drive App web socket: ('127.0.0.1', 29282)
[I  2021-02-04 11:59:41,068 | artella | plugin:setup_project:134] > Set Maya Workspace Path: D:/Dev/Artella

 ____________________________________
|             _____                  |
|            / ____|                 |
|  _ __ ___ | |  __  ___  __ _ _ __  |
| | '_ ` _ \| | |_ |/ _ \/ _` | '__| |
| | | | | | | |__| |  __/ (_| | |    |
| |_| |_| |_|\_____|\___|\__,_|_|    |
|____________________________________|

Red9 : Importing Language Map : language_english
INFO:Red9.startup.setup:Red9 StudioPack v3.0 : author: Mark Jackson
INFO:Red9.startup.setup:Red9 StudioPack Setup Calls :: Booting from >> C:/Users/User/Documents/maya/scripts/Red9
INFO:Red9.startup.setup:Red9 Icons Path already setup
INFO:Red9.startup.setup:Red9 Plug-in Path already setup
INFO:Red9.startup.setup:Red9 Script Path already setup : C:/Users/User/Documents/maya/scripts/Red9/core
INFO:Red9.startup.setup:Adding Red9Packages To Python Paths : C:/Users/User/Documents/maya/scripts/Red9/packages
INFO:Red9.startup.setup:Red9 StudioPack Complete!
Qt: Dead lock detected while activating a BlockingQueuedConnection: Sender is TmainThreadScriptExecutor(0x1b675835850), receiver is TmainThreadScriptExecutor(0x1b675835850)
Begin
mobject __eq__ already setup!
INFO:cgm.core.mrs.lib.batch_utils:Good Path: D:\Dev\Artella\SEU\content\RnD\WalletLeaver\template\WalletLeaver_template_01.mb
DEBUG:cgm.core.mrs.lib.batch_utils:process_blocks_rig >> WalletLeaver_template_01 ...
INFO:cgm.core.mrs.lib.batch_utils:New Path: D:\Dev\Artella\SEU\content\RnD\WalletLeaver\template\WalletLeaver_template_01_BUILD.mb
[I  2021-02-04 11:59:44,075 | artella | plugin:_before_open_check:203] > Opening file: "D:/Dev/Artella/SEU/content/RnD/WalletLeaver/template/WalletLeaver_template_01.mb"
[I  2021-02-04 11:59:44,081 | artella | plugin:validate_environment_for_callback:143] > validate_environment_for_callback for BeforeOpenCheck
[I  2021-02-04 11:59:44,085 | artella | plugin:_before_open_check:206] > Checking missing dependencies ...
INFO:Red9.core.Red9_Meta:"file Open" or "file new" called - Red9 MetaCache being cleared
Warning: file: C:\Users\User\Documents\maya\2019\prefs\filePathEditorRegistryPrefs.mel line 4: filePathEditor: Attribute 'aiImage.filename' is invalid or is not designated 'usedAsFilename'.
Warning: file: C:\Users\User\Documents\maya\2019\prefs\filePathEditorRegistryPrefs.mel line 5: filePathEditor: Attribute 'aiPhotometricLight.aiFilename' is invalid or is not designated 'usedAsFilename'.
Warning: file: C:\Users\User\Documents\maya\2019\prefs\filePathEditorRegistryPrefs.mel line 7: filePathEditor: Attribute 'aiVolume.filename' is invalid or is not designated 'usedAsFilename'.
Warning: line 1: filePathEditor: Attribute 'aiVolume.filename' and label 'VDB' have been saved already.
Initialized VP2.0 renderer {
  Version : 2016.11.44.12. Feature Level 4.
  Adapter : GeForce RTX 2070/PCIe/SSE2
  Vendor ID: 4318. Device ID : 16027
  Driver : .
  API : OpenGL V.4.6.
  Max texture size : 32768 * 32768.
  Max tex coords : 8
  Shader versions supported (Vertex: 4, Geometry: 4, Pixel 4).
  Shader compiler profile : (Best card profile)
  Active stereo support available : 0
  GPU Memory Limit : 8192 MB.
  CPU Memory Limit: 15422.9 MB.
}
OpenCL evaluator is attempting to initialize OpenCL.
Detected 2 OpenCL Platforms:
 0: NVIDIA Corporation. NVIDIA CUDA. OpenCL 1.2 CUDA 11.0.140.
 Supported extensions: cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics
 1: Intel(R) Corporation. Intel(R) OpenCL. OpenCL 2.1 .
 Supported extensions: cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_depth_images cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_icd cl_khr_image2d_from_buffer cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_spir
OpenCL evaluator choosing OpenCL platform NVIDIA Corporation.
OpenCL evaluator is unable to find a GPU device that can share VBOs with OpenGL.
Warning: line 1: filePathEditor: Attribute 'aiImage.filename' and label 'Image' have been saved already.
Warning: line 1: filePathEditor: Attribute 'aiPhotometricLight.aiFilename' and label 'IES' have been saved already.
Successfully imported python module 'arnold'
Successfully imported python module 'mtoa'
Cannot open file ':/expression.svg', because: No such file or directory
Cannot open file ':/expression.svg', because: No such file or directory
Cannot open file ':/expression.svg', because: No such file or directory
Cannot open file ':/expression.svg', because: No such file or directory
Successfully registered renderer 'arnold'
File read in  4.4 seconds.
[I  2021-02-04 11:59:49,170 | artella | plugin:validate_environment_for_callback:143] > validate_environment_for_callback for AfterOpen
|cgm.core.mrs.blocks.master.rig_prechecks| >> Time >> = 0.0000 seconds
|cgm.core.lib.search_utils.get_nodeSnapShot| >> Time >> = 0.1160 seconds
|cgm.core.mrs.RigBlocks.fnc_get_nodeSnapShot| >> Time >> = 0.1180 seconds
Warning: Object, 'rig', skipped. It is already a child of the parent, 'master'.
Warning: Object, 'deform', skipped. It is already a child of the parent, 'rig'.
Warning: Object, 'noTransform', skipped. It is already a child of the parent, 'rig'.
Warning: Object, 'master|geo', skipped. It is already a child of the parent, 'master'.
Warning: Object, 'skeleton', skipped. It is already a child of the parent, 'master'.
Warning: Object, 'parts', skipped. It is already a child of the parent, 'rig'.
Warning: Object, 'worldSpaceObjects', skipped. It is already a child of the parent, 'rig'.
Warning: Object, 'puppetSpaceObjects', skipped. It is already a child of the parent, 'rig'.
WARNING:cgm.core.mrs.RigBlocks:|fnc_rigNeed| >> Versions don't match: rigNull: None | buildModule: 21.4.1.01
INFO:cgm.core.mrs.RigBlocks:|fnc_bufferDat| >> Creating masterControl...
Warning: Object, 'rig', skipped. It is already a child of the parent, 'master'.
Warning: Object, 'deform', skipped. It is already a child of the parent, 'rig'.
Warning: Object, 'noTransform', skipped. It is already a child of the parent, 'rig'.
Warning: Object, 'master|geo', skipped. It is already a child of the parent, 'master'.
Warning: Object, 'skeleton', skipped. It is already a child of the parent, 'master'.
Warning: Object, 'parts', skipped. It is already a child of the parent, 'rig'.
Warning: Object, 'worldSpaceObjects', skipped. It is already a child of the parent, 'rig'.
Warning: Object, 'puppetSpaceObjects', skipped. It is already a child of the parent, 'rig'.
|cgm.core.mrs.lib.puppet_utils.layer_verify| >> Time >> = 0.0020 seconds
INFO:cgm.core.mrs.RigBlocks:|cgmRigPuppet.verify_masterControl| >> Finding size from rigBlock...
INFO:cgm.core.mrs.RigBlocks:|cgmRigMaster.rebuildControlCurve| >> Finding size from rigBlock...
Warning: Nothing is selected. Select objects or components to delete.
Warning: Could not find an exact match for font 'arial, 28.0pt'.
Using 'Arial, 28.2pt' instead.
Func: create_text
/// Args ///---------------------------------------------------------------------------
    arg 0: master
/// Kws... ///---------------------------------------------------------------------------
    kw: ('font', 'arial')
    kw: ('size', 118.99999999999999)
/// wrapper   ///---------------------------------------------------------------------------
 file: C:/Users/User/Documents/maya/scripts\cgm\core\cgm_General.py
  Args...
      master
  KWS...
      font : arial
      size : 119.0
  Local dat...
{'_str_func': 'cgm.core.lib.curve_Utils.create_text',
 'arg': u'master',
 'err': RuntimeError(u'Failed to create the text with the specified font\n',),
 'error': RuntimeError(u'Failed to create the text with the specified font\n',),
 'func': <function create_text at 0x000001B6760054A8>,
 'i': 0,
 'items': ('size', 118.99999999999999),
 'res': None,
 't1': 1612439989.943,
 'traceback': <traceback object at 0x000001B61BE87C08>}
...///
/// rebuildMasterShapes   ///---------------------------------------------------------------------------
 file: C:/Users/User/Documents/maya/scripts\cgm\core\mrs\RigBlocks.py
  KWS...
      size : [170.0, 0.1, 170.0]
  Local dat...
{'_average': 170.0,
 '_crv': u'curve37',
 '_offsetSize': 17.0,
 '_short': u'|cgmObject',
 '_size': 255.0,
 '_str_func': 'cgmRigMaster.rebuildControlCurve',
 'err': RuntimeError(u'Failed to create the text with the specified font\n',),
 'font': 'arial',
 'l_offsetCrvs': [u'offsetNurbsCurve1',
                  u'offsetNurbsCurve2',
                  u'offsetNurbsCurve3',
                  u'offsetNurbsCurve4'],
 'l_shapes': [],
 'mBlock': (node: 'master_masterBlock' | mClass: cgmRigBlock | class: <class 'cgm.core.mrs.RigBlocks.cgmRigBlock'>),
 'mCrv': Dead mNode : Last good dag path was: |curve37,
 'mHandleFactory': <class 'cgm.core.mrs.lib.blockShapes_utils.handleFactory'>(root: (node: 'cgmObject' | mClass: cgmRigMaster | class: <class 'cgm.core.mrs.RigBlocks.cgmRigMaster'>) | mBlock: None),
 'nameSize': 170.0,
 'offsetShape': u'offsetNurbsCurve4',
 'self': (node: 'cgmObject' | mClass: cgmRigMaster | class: <class 'cgm.core.mrs.RigBlocks.cgmRigMaster'>),
 'shape': u'|curve37|curveShape206',
 'size': [170.0, 0.0, 170.0]}
{'font': 'arial', '_str_func': 'cgmRigMaster.rebuildControlCurve', 'err': RuntimeError(u'Failed to create the text with the specified font\n',), 'mCrv': Dead mNode : Last good dag path was: |curve37, '_short': u'|cgmObject', '_crv': u'curve37', '_offsetSize': 17.0, '_average': 170.0, 'shape': u'|curve37|curveShape206', 'l_offsetCrvs': [u'offsetNurbsCurve1', u'offsetNurbsCurve2', u'offsetNurbsCurve3', u'offsetNurbsCurve4'], 'mHandleFactory': <class 'cgm.core.mrs.lib.blockShapes_utils.handleFactory'>(root: (node: 'cgmObject' | mClass: cgmRigMaster | class: <class 'cgm.core.mrs.RigBlocks.cgmRigMaster'>) | mBlock: None), 'l_shapes': [], 'mBlock': (node: 'master_masterBlock' | mClass: cgmRigBlock | class: <class 'cgm.core.mrs.RigBlocks.cgmRigBlock'>), '_size': 255.0, 'size': [170.0, 0.0, 170.0], 'self': (node: 'cgmObject' | mClass: cgmRigMaster | class: <class 'cgm.core.mrs.RigBlocks.cgmRigMaster'>), 'nameSize': 170.0, 'offsetShape': u'offsetNurbsCurve4'}
...///
/// __verify__   ///---------------------------------------------------------------------------
 file: C:/Users/User/Documents/maya/scripts\cgm\core\mrs\RigBlocks.py
  KWS...
      size : [170.0, 0.1, 170.0]
  Local dat...
{'_shapes': [],
 '_short': u'|cgmObject',
 '_str_func': 'cgmRigMaster.__verify__',
 'err': RuntimeError(u'Failed to create the text with the specified font\n',),
 'puppet': (node: 'master_puppetNetwork' | mClass: cgmRigPuppet | class: <class 'cgm.core.mrs.RigBlocks.cgmRigPuppet'>),
 'self': (node: 'cgmObject' | mClass: cgmRigMaster | class: <class 'cgm.core.mrs.RigBlocks.cgmRigMaster'>)}
{'err': RuntimeError(u'Failed to create the text with the specified font\n',), '_short': u'|cgmObject', '_shapes': [], 'puppet': (node: 'master_puppetNetwork' | mClass: cgmRigPuppet | class: <class 'cgm.core.mrs.RigBlocks.cgmRigPuppet'>), '_str_func': 'cgmRigMaster.__verify__', 'self': (node: 'cgmObject' | mClass: cgmRigMaster | class: <class 'cgm.core.mrs.RigBlocks.cgmRigMaster'>)}
...///
/// __init__   ///---------------------------------------------------------------------------
 file: C:/Users/User/Documents/maya/scripts\cgm\core\mrs\RigBlocks.py
  KWS...
      puppet : (node: 'master_puppetNetwork' | mClass: cgmRigPuppet | class: <class 'cgm.core.mrs.RigBlocks.cgmRigPuppet'>)
      size : [170.0, 0.1, 170.0]
  Local dat...
{'_callSize': [170.0, 0.1, 170.0],
 '_sel': None,
 '_size': [170.0, 0.0, 170.0],
 '_str_func': 'cgmRigMaster.__init__',
 'doVerify': False,
 'err': RuntimeError(u'Failed to create the text with the specified font\n',),
 'self': (node: 'cgmObject' | mClass: cgmRigMaster | class: <class 'cgm.core.mrs.RigBlocks.cgmRigMaster'>)}
{'_sel': None, 'err': RuntimeError(u'Failed to create the text with the specified font\n',), 'doVerify': False, '_callSize': [170.0, 0.1, 170.0], 'self': (node: 'cgmObject' | mClass: cgmRigMaster | class: <class 'cgm.core.mrs.RigBlocks.cgmRigMaster'>), '_str_func': 'cgmRigMaster.__init__', '_size': [170.0, 0.0, 170.0]}
...///
/// verify_masterControl   ///---------------------------------------------------------------------------
 file: C:/Users/User/Documents/maya/scripts\cgm\core\mrs\RigBlocks.py
  KWS...
      size : [170.0, 0.0, 170.0]
  Local dat...
{'_size': [170.0, 0.0, 170.0],
 '_str_func': 'cgmRigPuppet.verify_masterControl',
 'bb': [170.0, 0.0, 170.0],
 'err': RuntimeError(u'Failed to create the text with the specified font\n',),
 'mBlock': (node: 'master_masterBlock' | mClass: cgmRigBlock | class: <class 'cgm.core.mrs.RigBlocks.cgmRigBlock'>),
 'mMasterControl': None,
 'mMasterNull': (node: 'master' | mClass: cgmMasterNull | class: <class 'cgm.core.cgm_PuppetMeta.cgmMasterNull'>),
 'self': (node: 'master_puppetNetwork' | mClass: cgmRigPuppet | class: <class 'cgm.core.mrs.RigBlocks.cgmRigPuppet'>)}
{'err': RuntimeError(u'Failed to create the text with the specified font\n',), 'bb': [170.0, 0.0, 170.0], 'self': (node: 'master_puppetNetwork' | mClass: cgmRigPuppet | class: <class 'cgm.core.mrs.RigBlocks.cgmRigPuppet'>), 'mMasterNull': (node: 'master' | mClass: cgmMasterNull | class: <class 'cgm.core.cgm_PuppetMeta.cgmMasterNull'>), '_str_func': 'cgmRigPuppet.verify_masterControl', '_size': [170.0, 0.0, 170.0], 'mMasterControl': None, 'mBlock': (node: 'master_masterBlock' | mClass: cgmRigBlock | class: <class 'cgm.core.mrs.RigBlocks.cgmRigBlock'>)}
...///
/// fnc_bufferDat   ///---------------------------------------------------------------------------
 file: C:/Users/User/Documents/maya/scripts\cgm\core\mrs\RigBlocks.py
  Local dat...
{'_blockType': u'master',
 '_buildVersion': '21.4.1.01',
 '_d': {'f_shapeOffset': 1.7,
        'mMasterNull': (node: 'master' | mClass: cgmMasterNull | class: <class 'cgm.core.cgm_PuppetMeta.cgmMasterNull'>),
        'mirrorDirection': 'Centre'},
 '_d_callKWS': {'autoBuild': True,
                'forceNew': True,
                'ignoreRigCheck': False,
                'rigBlock': (node: 'master_masterBlock' | mClass: cgmRigBlock | class: <class 'cgm.core.mrs.RigBlocks.cgmRigBlock'>)},
 '_mModule': None,
 '_mModuleParent': None,
 '_mPuppet': (node: 'master_puppetNetwork' | mClass: cgmRigPuppet | class: <class 'cgm.core.mrs.RigBlocks.cgmRigPuppet'>),
 '_mRigNull': None,
 '_str_func': 'fnc_bufferDat',
 '_version': None,
 'err': RuntimeError(u'Failed to create the text with the specified font\n',),
 'self': <class 'cgm.core.mrs.RigBlocks.rigFactory'>(rigBlock: |cgmRigBlocksGroup|master_masterBlock)}
{'_blockType': u'master', '_mModuleParent': None, 'err': RuntimeError(u'Failed to create the text with the specified font\n',), '_mPuppet': (node: 'master_puppetNetwork' | mClass: cgmRigPuppet | class: <class 'cgm.core.mrs.RigBlocks.cgmRigPuppet'>), '_mRigNull': None, '_version': None, '_mModule': None, '_str_func': 'fnc_bufferDat', '_buildVersion': '21.4.1.01', '_d': {'mirrorDirection': 'Centre', 'f_shapeOffset': 1.7, 'mMasterNull': (node: 'master' | mClass: cgmMasterNull | class: <class 'cgm.core.cgm_PuppetMeta.cgmMasterNull'>)}, 'self': <class 'cgm.core.mrs.RigBlocks.rigFactory'>(rigBlock: |cgmRigBlocksGroup|master_masterBlock), '_d_callKWS': {'forceNew': True, 'ignoreRigCheck': False, 'autoBuild': True, 'rigBlock': (node: 'master_masterBlock' | mClass: cgmRigBlock | class: <class 'cgm.core.mrs.RigBlocks.cgmRigBlock'>)}}
...///
ERROR:cgm.core.mrs.lib.batch_utils:Failed to create the text with the specified font

INFO:cgm.core.mrs.lib.batch_utils:|process_blocks_rig| >> Total Time >> = 00:00:01 seconds
INFO:cgm.core.mrs.lib.batch_utils:D:/Dev/Artella/SEU/content/RnD/WalletLeaver/template/WalletLeaver_template_01_BUILD.mb
End
>>>

**Comment by jjburton** [comment]
We looked through it. Looks like a weird bug with a standard maya call not working.
import maya.cmds as mc
mc.textCurves(cch = False, t = 'elephant')

Working through it.

**Comment by jjburton** [comment]
Added bypass for the text curve
