### ISSUE TITLE
Nothing happen when push the form 

### ISSUE THREAD

**Issue by broco1001** [jjburton/cgmTools#202]
![image](https://user-images.githubusercontent.com/77574628/107180043-7e882180-6a0a-11eb-9e84-213fef9dbd82.png)

I'm trying to the next step from define to the form , but when i push the form buttom nothing happen ..

**Comment by jjburton** [comment]
@broco1001 | hands are a special block type called a blockFrame. They don't build normally.  Check the docs in the wikki here or there is a vid on the Monkey King series when I use it or one from last summer.

**Comment by broco1001** [comment]
> @broco1001 | hands are a special block type called a blockFrame. They don't build normally. Check the docs in the wikki here or there is a vid on the Monkey King series when I use it or one from last summer.

I got it, I have to verify driver the hand, i miss that parts in video   ..thanks
