### ISSUE TITLE
Latest version - Scene - "rig" is displaying files from previous animations loaded

### ISSUE THREAD

**Issue by PhaserlockBren** [jjburton/cgmTools#229]
![scene_rig](https://user-images.githubusercontent.com/68934362/115428062-a1337500-a1c7-11eb-9702-76b74996053d.png)
![image](https://user-images.githubusercontent.com/68934362/115428115-adb7cd80-a1c7-11eb-8f96-ed517f8ed561.png)

**Comment by jjburton** [comment]
I've been reworking the walker. There are probably some bugs. I'll see if I can duplicate that and get it fixed soon.
