### ISSUE TITLE
Suggestion for Scene

### ISSUE THREAD

**Issue by PhaserlockBren** [jjburton/cgmTools#233]
Just had a thought for a future addition - Dont laugh - it sounds like I'm being lazy, but how bout adding an option in scene / rig -right click menu for "reference for export" which starts a new scene closing out the current scene and starts " new scene" then references the file, setting up for exporting a rig.

**Comment by jjburton** [comment]
Not a bad idea. Noted.

**Comment by jjburton** [comment]
Will be in next push In version pop up menu: Create SubTypeRef
