### ISSUE TITLE
Scene folder and file construction erroring

### ISSUE THREAD

**Issue by benngarnish** [jjburton/cgmTools#238]
I hope the gif illustrates the issues...
Trying to create a new template in this case causes an issues and doesn't create a new folder, instead throws it within the first created folder.
![scene_erroring](https://user-images.githubusercontent.com/1122587/117975159-49031500-b326-11eb-877c-a1c01662383e.gif)

**Comment by jjburton** [comment]
@benngarnish | can't seem to replicate this on current pipeline branch with fixes. Lemme know if you see it after the next merge.

**Comment by benngarnish** [comment]
Thanks I’ll check this tomorrow as I see there’s been a merge into MRSSDEV 🤘

**Comment by jjburton** [comment]
Looked again, can't replicate
