### ISSUE TITLE
It appears " export rig" isn't working in maya.py

### ISSUE THREAD

**Issue by PhaserlockBren** [jjburton/cgmTools#239]
No file is being saved when I export the rig via maya.py
Script editor:
cgm.core.mrs.Scene : INFO :
{'animationName': 'Raptor_Rig_01.mb',
 'bakeSetName': 'bake_tdSet',
 'categoryExportPath': 'D:/Dropbox (Phaser Lock INC)/Phaser Lock Team/PrimalHunt/Art/FINAL/EXPORT/Dinosaurs',
 'deleteSetName': 'delete_tdSet',
 'euler': True,
 'exportAnimPath': 'D:/Dropbox (Phaser Lock INC)/Phaser Lock Team/PrimalHunt/Art/FINAL/EXPORT/Dinosaurs/Raptor/Rig',
 'exportAssetPath': 'D:/Dropbox (Phaser Lock INC)/Phaser Lock Team/PrimalHunt/Art/FINAL/EXPORT/Dinosaurs/Raptor',
 'exportName': 'Raptor_Rig.fbx',
 'exportObjs': ['Raptor:master'],
 'exportSetName': 'export_tdSet',
 'mode': 3,
 'removeNamespace': True,
 'subType': 'Rig',
 'tangent': 'auto',
 'updateAndIncrement': None,
 'workspace': 'D:/Dropbox (Phaser Lock INC)/Phaser Lock Team/PrimalHunt/Art/FINAL',
 'zeroRoot': True}
cgm.core.mrs.Scene : ERROR : Invalid file:
cgm.core.mrs.Scene : INFO : |BatchExport| >> Total Time >> = 0.0260 seconds
End
>>>

**Comment by jjburton** [comment]
Should work fine as long as not from the batch. Remember to setup your rig file referencing the rig.

**Comment by PhaserlockBren** [comment]
Yeah – rig referenced – Just not exporting an actual fbx anywhere that I can find. It exports fine without Maya.py          Bren Wilson   Animation Lead  From: Josh BurtonSent: Tuesday, May 18, 2021 12:58 PMTo: jjburton/cgmToolsCc: PhaserlockBren; AuthorSubject: Re: [jjburton/cgmTools] It appears " export rig" isn't working in maya.py (#239) Should work fine as long as not from the batch. Remember to setup your rig file referencing the rig.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jjburton** [comment]
you're css copy paste is fun :)

I've been exporting rigs fine. I'll verify again...

Just did it. Worked fine. Ping me tonight or when you have time.

**Comment by jjburton** [comment]
Exported your file okay:

1) I went to the asset dir and found the rig file
2) created a ref rig file
3) selected master, export rig via maya py
4) checked export - D:\Dropbox\XXXXXXXX\export\XXXXXX\XXXXX

I'm gonna update the doc for exporting a rig this week.
