### ISSUE TITLE
MK1 UnityMed Base Template

### ISSUE THREAD

**Issue by jjburton** [jjburton/cgmTools#24]
Doing a new template to test the new scale changes.

### Model
- [x] Get Matt's updates into a new master geo file

### Template
- [x] Template with new setup
- [x] Use hand block
- [x] Build
- [ ] Push up the unityMedium asset to test?

**Comment by jjburton** [comment]
### Joints
 Was getting a bug with math on our joint orient call. Bokser assisted in addressing it

**Comment by jjburton** [comment]
Proxy - 
The normals are still messed up sometimes on proxy gen.
- [ ] See if the calls are using our new rebuild method
- [ ] Investigate if our loft curves need to be reversed

 if they're using

**Comment by jjburton** [comment]
### Build Issues
- [ ] Fingers generating extra dags

**Comment by jjburton** [comment]
### Vector mirror
The vector mirror bug was odd. One of our calls was generating slightly off vectors. Replaced it and wrote a couple of calls to make it easier.

The core issue seems to be that scale affects one of our calls vector return making the mirror functionality off when the target or source objects are scaled. Which is often for the templates.

@dbokser - Not sure how to resolve the core call. The current method is holding up but I can't imagine this one won't come again. 

`reflectAim = mObj.getAxisVector('z+',asEuclid=True).reflect( reflectionVector)
                reflectUp  = mObj.getAxisVector('y+',asEuclid=True).reflect( reflectionVector)
                #reflectAim = mObj.getTransformDirection( MATH.Vector3(0,0,1)).reflect( reflectionVector )
                #reflectUp  = mObj.getTransformDirection( MATH.Vector3(0,1,0)).reflect( reflectionVector )`

**Comment by dbokser** [comment]
transformDirection should work as expected now

https://github.com/jjburton/cgmTools/commit/ffbd7ec56f05abdba209a642394361aed2cfa9a2

**Comment by jjburton** [comment]
### Form loft setup...

Still has that seam on some setups. Try
loft
- uniform | off
- degree | cubic?
rebuild
- bezier is fine
- spans v needs min count to get rig of seam
- degree U | linear
- spans V | 20 to avoid seam
-degree V| linear

Think just don't connect main loft degree to the change

**Comment by jjburton** [comment]
### Abnormal Normals
Still getting weird normal issues. Trying some idea...

**Comment by jjburton** [comment]
### Proxy mesh speed
Finger Start time - 9.6sec

- rigFactory init is 1.7 of it....why do we need that?
- Each loft mesh is about .8 seconds
- Shape parent in place is about .03 sec. If the new method is indeed faster then that could be huge savings on rig build in general.

**Comment by jjburton** [comment]
### Loft curves
They're not sized the same. Need to fix.

Added a baseSize option for create_from_name so that they can have a 1.0 unit base if desired. Off by default
