### ISSUE TITLE
Renaming Sub-type

### ISSUE THREAD

**Issue by PhaserlockBren** [jjburton/cgmTools#253]
when re-naming as asset or subtype - itd be keen if the original name appeared in the window where you will be entering the new name as opposed to a blank window - Many times, i might be making minor corrections to the naming convention - adding an underscore - or number padding...etc... being able to simply enter the modification rather than re-typing the full name would be faster

**Comment by jjburton** [comment]
Should be easy enough. Will do.

**Comment by jjburton** [comment]
will be in next push
