### ISSUE TITLE
Updating blocks

### ISSUE THREAD

**Issue by benngarnish** [jjburton/cgmTools#26]
When I update my blocks the old <template> block stays and a new <form> block is created giving me 2 blocks of the same rig block. For example, I have 2 spine blocks, one is my old template block and also a new def block that was created by the update block function.
If I try and use the Load state on the block dat the new block doesn't do anything.

Not sure what is happening here. 
I end up re-building the entire template file :-(

**Comment by jjburton** [comment]
@benngarnish - Can you throw one of these files up so I can test? Thanks!

**Comment by jjburton** [comment]
@benngarnish  - pretty sure new build will fix. Will be merging
