### ISSUE TITLE
Im getting a couple of errors with creating new animations in scene:

### ISSUE THREAD

**Issue by PhaserlockBren** [jjburton/cgmTools#263]
Firstly - The " New Anim" button is reading as " Save New Version" unless I switch away from Anim and back - Then its labeled as expected.

Then when creating the new animation Im getting this:
# Warning: Item not found: ANIM_Test # 
# Error: TypeError: file C:\Program Files\Autodesk\Maya2020\bin\python27.zip\ntpath.py line 115: object of type 'NoneType' has no len() # 

It is creating the animation directory but its putting in inside the currently hi-lighted folder that exists in the " Anim" column.

**Comment by jjburton** [comment]
@PhaserlockBren | did this clear up when you got back on MRSDEV?
