### ISSUE TITLE
Error when trying to save an unnamed file into an asset with existing files

### ISSUE THREAD

**Issue by dbokser** [jjburton/cgmTools#279]
Issue: Error when trying to "Save New Version" with an unnamed scene file with existing files in the asset

Error Msg:
base_crouch_walk_1.ma
# Error: ValueError: file C:\Users\dboks\Documents\cgmTools\mayaTools\cgm\core\mrs\Scene.py line 3338: need more than 1 value to unpack # 

Expected Result:
The file is saved as a new version in the asset directory regardless of its current name or otherwise

**Comment by jjburton** [comment]
Fixed. will be in next push
