### ISSUE TITLE
Scene shows an error upon loading

### ISSUE THREAD

**Issue by dbokser** [jjburton/cgmTools#281]
`
# cgm.core.cgm_General : Release: MRSDAILY | 21.10.04.1
# Error: Value is out of range: 1
# Traceback (most recent call last):
#   File "<maya console>", line 3, in <module>
#   File "C:\Users\dboks\Documents\cgmTools\mayaTools\cgm\core\lib\zoo\typeFactories.py", line 99, in __call__
#     instance = super( _InstanceTrackerType, self ).__call__( *a, **kw )
#   File "C:\Users\dboks\Documents\cgmTools\mayaTools\cgm\core\classes\GuiFactory.py", line 972, in __init__
#     except Exception,err:cgmGEN.cgmException(Exception,err)
#   File "C:\Users\dboks\Documents\cgmTools\mayaTools\cgm\core\classes\GuiFactory.py", line 965, in __init__
#     self.post_init(self,*a,**kw)
#   File "C:\Users\dboks\Documents\cgmTools\mayaTools\cgm\core\mrs\Scene.py", line 211, in post_init
#     self.LoadProject(self.var_lastProject.getValue())
#   File "C:\Users\dboks\Documents\cgmTools\mayaTools\cgm\core\mrs\Scene.py", line 3606, in LoadProject
#     self.uiProject_refreshDisplay()
#   File "C:\Users\dboks\Documents\cgmTools\mayaTools\cgm\core\mrs\Scene.py", line 1528, in uiProject_refreshDisplay
#     self.assetList['scrollList'].selectByIdx(0)
#   File "C:\Users\dboks\Documents\cgmTools\mayaTools\cgm\core\classes\GuiFactory.py", line 2375, in selectByIdx
#     self( e=True, selectIndexedItem=idx+1 )  #indices are 1-based in mel land - fuuuuuuu alias!!!
#   File "C:\Users\dboks\Documents\cgmTools\mayaTools\cgm\core\lib\zoo\baseMelUI.py", line 165, in __call__
#     return self.WIDGET_CMD( unicode( self ), *a, **kw )
# RuntimeError: Value is out of range: 1 # `

**Comment by jjburton** [comment]
Fixed | MRSDAILY 21.10.4.2
