### ISSUE TITLE
Scene crashing

### ISSUE THREAD

**Issue by benngarnish** [jjburton/cgmTools#284]
latest pull in MRSDAILY branch causes maya to crash if you try and change to a different folder location.
Replicate:
select character
change from geo group to template
maya crashes

**Comment by jjburton** [comment]
Can you send me one of the files to test with? I've not seen a maya crash like that and I'm in scene all over the place every day. There was one crash I fixed this week that had to do with a structure not having any subtype dirs but that's sorted.
