### ISSUE TITLE
Chest Ik not naming correctly after build

### ISSUE THREAD

**Issue by benngarnish** [jjburton/cgmTools#292]
Currently the chest IK builds with the name `spine_2_ik_anim`

**Comment by jjburton** [comment]
Check your name list? If you changed handle counts it might not be getting to chest in the list now.

**Comment by jjburton** [comment]
Cool, I'll see if I can replicate.

**Comment by jjburton** [comment]
The new block create will hopefully sort this. This is a matter of order of operations with when prerig is build and names are set.
