### ISSUE TITLE
Neck and Head direct_anim controllers not hiding

### ISSUE THREAD

**Issue by benngarnish** [jjburton/cgmTools#304]
I still have the issue of the head and neck direct anim controllers not being connected to the attribute `Vis Direct`
A possible bug 🐞 ?

**Comment by jjburton** [comment]
fixin to build one, lemme check

**Comment by jjburton** [comment]
@benngarnish | are you using proxyDirect or just control shapes?

**Comment by jjburton** [comment]
Fixed in next push
