### ISSUE TITLE
Bugs - Week of 04.29.2019

### ISSUE THREAD

**Issue by jjburton** [jjburton/cgmTools#40]
### Segment
- [x] proxy mesh on spine at least isn't matching the form mesh
- [x] Last ik shape isn't conforming well
- [x] pelvis fk control - vestigial?

### LIMB
- [x] world IK seems weird on build
- [x] foot top loft curve doesn't match lower
- [x] Bokser wants the ik base to hide with the root
- [x] Finger/thumb settings placement to base

### General
- [ ] Focus weirdness report from Benn. Can't replicate.

**Comment by benngarnish** [comment]
Recreating a joint state on a block doesn't reconnect the hierarchy again.
This is when using "below" as the contextual method.
If you switch to self then the joints rebuild correctly.

**Comment by jjburton** [comment]
@benngarnish - Looking at your template I can't replicate this. Taking chat to discord

**Comment by benngarnish** [comment]
ERROR:
`# cgm.core.mrs.Builder : ============================================================================================================================= # 
# Error: cgm.core.mrs.lib.block_utils : [char_masterBlock] No form or prerig handles found # 
# Error: cgm.core.mrs.lib.block_utils : [char_masterBlock] No form or prerig handles found # `

**Comment by jjburton** [comment]
@benngarnish  - user confusion. Will change the error to a debug so it's not alarming:)
