### ISSUE TITLE
Building head neck short block

### ISSUE THREAD

**Issue by benngarnish** [jjburton/cgmTools#47]
`/// verify   ///----------------------------------------------------------------------------------------------------
 file: C:/Users/BennGarnish/Documents/maya/scripts\cgm\core\mrs\lib\block_utils.py
  Local dat...
{'_mBlockModule': <module 'cgm.core.mrs.blocks.organic.head' from 'C:/Users/BennGarnish/Documents/maya/scripts\cgm\core\mrs\blocks\organic\head.pyc'>,
 '_short': u'|head',
 '_side': None,
 '_str_func': 'verify',
 '_type': u'head',
 'blockType': 'head',
 'err': TypeError('coercing to Unicode: need string or buffer, NoneType found',),
 'forceReset': False,
 'self': (node: 'head' | mClass: cgmRigBlock | class: <class 'cgm.core.mrs.RigBlocks.cgmRigBlock'>),
 'side': None,
 'size': None}
...///
# Error: cgm.core.mrs.RigBlocks : |cgmRigBlock.__init__| >> Failed to initialize properly! ================================================================================ # 
/// __init__   ///----------------------------------------------------------------------------------------------------
 file: C:/Users/BennGarnish/Documents/maya/scripts\cgm\core\mrs\RigBlocks.py
  KWS...
      blockProfile : neck short
      buildProfile : unityMed
      side : None
      size : None
  Local dat...
{'_baseSize': None,
 '_blockModule': <module 'cgm.core.mrs.blocks.organic.head' from 'C:/Users/BennGarnish/Documents/maya/scripts\cgm\core\mrs\blocks\organic\head.pyc'>,
 '_callSize': [15.2, 23.2, 19.7],
 '_doVerify': True,
 '_justCreated': True,
 '_postState': None,
 '_sel': [],
 '_side': None,
 '_size': None,
 '_sizeMode': None,
 '_str_func': 'cgmRigBlock.__init__',
 'autoForm': True,
 'blockParent': None,
 'blockType': 'head',
 'err': TypeError('coercing to Unicode: need string or buffer, NoneType found',),
 'kw_blockProfile': 'neck short',
 'kw_name': None,
 'node': None,
 'self': (node: 'head' | mClass: cgmRigBlock | class: <class 'cgm.core.mrs.RigBlocks.cgmRigBlock'>)}
...///
# cgm.core.cgm_Meta : |createMetaNode| >> mType: cgmRigBlock | class: <class 'cgm.core.mrs.RigBlocks.cgmRigBlock'> # 
# cgm.core.cgm_Meta : |createMetaNode| >> Kws... # 
# cgm.core.cgm_Meta :     kw: ('blockProfile', 'neck short') # 
# cgm.core.cgm_Meta :     kw: ('blockParent', None) # 
# cgm.core.cgm_Meta :     kw: ('blockType', 'head') # 
# cgm.core.cgm_Meta :     kw: ('buildProfile', u'unityMed') # 
# cgm.core.cgm_Meta :     kw: ('side', None) # 
# cgm.core.cgm_Meta :     kw: ('size', None) # 
# Error: cgm.core.cgm_Meta : coercing to Unicode: need string or buffer, NoneType found # 
/// createMetaNode   ///----------------------------------------------------------------------------------------------------
 file: C:/Users/BennGarnish/Documents/maya/scripts\cgm\core\cgm_Meta.py
  KWS...
      blockProfile : neck short
      blockParent : None
      blockType : head
      buildProfile : unityMed
      side : None
      size : None
  Local dat...
{'_call': <class 'cgm.core.mrs.RigBlocks.cgmRigBlock'>,
 '_r9ClassRegistry': {'MetaClass': <class 'Red9.core.Red9_Meta.MetaClass'>,
                      'MetaFacialRig': <class 'Red9.core.Red9_Meta.MetaFacialRig'>,
                      'MetaFacialRigSupport': <class 'Red9.core.Red9_Meta.MetaFacialRigSupport'>,
                      'MetaHIKCharacterNode': <class 'Red9.core.Red9_Meta.MetaHIKCharacterNode'>,
                      'MetaHIKControlSetNode': <class 'Red9.core.Red9_Meta.MetaHIKControlSetNode'>,
                      'MetaHIKPropertiesNode': <class 'Red9.core.Red9_Meta.MetaHIKPropertiesNode'>,
                      'MetaHUDNode': <class 'Red9.core.Red9_Meta.MetaHUDNode'>,
                      'MetaRig': <class 'Red9.core.Red9_Meta.MetaRig'>,
                      'MetaRigSubSystem': <class 'Red9.core.Red9_Meta.MetaRigSubSystem'>,
                      'MetaRigSupport': <class 'Red9.core.Red9_Meta.MetaRigSupport'>,
                      'cgmBlendShape': <class 'cgm.core.cgm_Deformers.cgmBlendShape'>,
                      'cgmBufferNode': <class 'cgm.core.cgm_Meta.cgmBufferNode'>,
                      'cgmControl': <class 'cgm.core.cgm_Meta.cgmControl'>,
                      'cgmDynParentGroup': <class 'cgm.core.cgm_RigMeta.cgmDynParentGroup'>,
                      'cgmDynamicMatch': <class 'cgm.core.cgm_RigMeta.cgmDynamicMatch'>,
                      'cgmDynamicSwitch': <class 'cgm.core.cgm_RigMeta.cgmDynamicSwitch'>,
                      'cgmEyeball': <class 'cgm.core.cgm_PuppetMeta.cgmEyeball'>,
                      'cgmEyeballBlock': <class 'cgm.core.cgm_PuppetMeta.cgmEyeballBlock'>,
                      'cgmEyebrow': <class 'cgm.core.cgm_PuppetMeta.cgmEyebrow'>,
                      'cgmEyebrowBlock': <class 'cgm.core.cgm_PuppetMeta.cgmEyebrowBlock'>,
                      'cgmEyelids': <class 'cgm.core.cgm_PuppetMeta.cgmEyelids'>,
                      'cgmInfoNode2': <class 'cgm.core.cgm_PuppetMeta.cgmInfoNode2'>,
                      'cgmLight': <class 'cgm.core.tools.lightLoomLite.cgmLight'>,
                      'cgmLightShape': <class 'cgm.core.tools.lightLoomLite.cgmLightShape'>,
                      'cgmLimb': <class 'cgm.core.cgm_PuppetMeta.cgmLimb'>,
                      'cgmMasterControl': <class 'cgm.core.cgm_PuppetMeta.cgmMasterControl'>,
                      'cgmMasterControlOLD': <class 'cgm.core.cgm_PuppetMeta.cgmMasterControlOLD'>,
                      'cgmMasterNull': <class 'cgm.core.cgm_PuppetMeta.cgmMasterNull'>,
                      'cgmModule': <class 'cgm.core.cgm_PuppetMeta.cgmModule'>,
                      'cgmModuleBufferNode': <class 'cgm.core.cgm_PuppetMeta.cgmModuleBufferNode'>,
                      'cgmMorpheusPuppet': <class 'cgm.core.cgm_PuppetMeta.cgmMorpheusPuppet'>,
                      'cgmMouthNose': <class 'cgm.core.cgm_PuppetMeta.cgmMouthNose'>,
                      'cgmMouthNoseBlock': <class 'cgm.core.cgm_PuppetMeta.cgmMouthNoseBlock'>,
                      'cgmNode': <class 'cgm.core.cgm_Meta.cgmNode'>,
                      'cgmNodeOLD': <class 'cgm.core.cgm_Meta.cgmNodeOLD'>,
                      'cgmObject': <class 'cgm.core.cgm_Meta.cgmObject'>,
                      'cgmObjectOLD': <class 'cgm.core.cgm_Meta.cgmObjectOLD'>,
                      'cgmObjectSet': <class 'cgm.core.cgm_Meta.cgmObjectSet'>,
                      'cgmPuppet': <class 'cgm.core.cgm_PuppetMeta.cgmPuppet'>,
                      'cgmPuppetOLD': <class 'cgm.core.cgm_PuppetMeta.cgmPuppetOLD'>,
                      'cgmRigBlock': <class 'cgm.core.mrs.RigBlocks.cgmRigBlock'>,
                      'cgmRigBlockHandle': <class 'cgm.core.mrs.RigBlocks.cgmRigBlockHandle'>,
                      'cgmRigBlockOLD': <class 'cgm.core.cgm_PuppetMeta.cgmRigBlockOLD'>,
                      'cgmRigMaster': <class 'cgm.core.mrs.RigBlocks.cgmRigMaster'>,
                      'cgmRigModule': <class 'cgm.core.mrs.RigBlocks.cgmRigModule'>,
                      'cgmRigPuppet': <class 'cgm.core.mrs.RigBlocks.cgmRigPuppet'>,
                      'cgmSimpleBSFace': <class 'cgm.core.cgm_PuppetMeta.cgmSimpleBSFace'>,
                      'cgmTest': <class 'cgm.core.cgm_Meta.cgmTest'>},
 '_str_func': 'createMetaNode',
 'arg': 'coercing to Unicode: need string or buffer, NoneType found',
 'err': TypeError('coercing to Unicode: need string or buffer, NoneType found',),
 'items': ('size', None),
 'mType': 'cgmRigBlock'}
...///
# cgm.core.cgm_General : Func: uiFunc_block_create # 
# cgm.core.cgm_General : args: ('head', 'neck short') # 
# cgm.core.cgm_General : coercing to Unicode: need string or buffer, NoneType found # 
/// __call__   ///----------------------------------------------------------------------------------------------------
 file: C:/Users/BennGarnish/Documents/maya/scripts\cgm\core\cgm_General.py
  Args...
      False
  Local dat...
{'a': 'coercing to Unicode: need string or buffer, NoneType found',
 'err': TypeError('coercing to Unicode: need string or buffer, NoneType found',),
 'self': <cgm.core.cgm_General.Callback object at 0x000002B1A8192630>}
...///
# Error: TypeError: file C:/Users/BennGarnish/Documents/maya/scripts\cgm\core\mrs\lib\block_utils.py line 549: coercing to Unicode: need string or buffer, NoneType found # 
`

**Comment by benngarnish** [comment]
Same issue in both MRS and MRSDEV branches

**Comment by jjburton** [comment]
Added to punch list. I'll hit this week.

**Comment by jjburton** [comment]
@benngarnish - can't replicate. Just built a neck short fine. Send me a file.

**Comment by bgarnish** [comment]
It’s a fresh build.
