### ISSUE TITLE
Muzzle refresh

### ISSUE THREAD

**Issue by jjburton** [jjburton/cgmTools#49]
- [x] Define
- [ ] Form
- [x] Pre
- [x] Joint
- [x] Rig

Rig pass 2
- [x] Add blendable driver on nose for muzzle
- [x] Add aim back to corner on handle chain, maybe when only one handle is present?
- [x] Attribute multiplier for cheek push/pull

**Comment by jjburton** [comment]
- [ ] Noticed an issue with the ribbon setup. Resolving
- [ ] Lip corner - need to make it follow the control and not the influence now that we have that aiming

**Comment by bgarnish** [comment]
So I have some questions. 
What does the form state do apart from help with proxy creation?
Do the joints slide across the surface that you’ve created?

I’m finding pulling and pushing all the “controller” object a bit of a faff taking a while to form the face of my character. I don’t really want to have to do this on multiple characters especially if I’m just testing to find correct joint placement and see how the rig build and works with the model. 

If the joints do require surface information from the form state is there a simpler route? Just planes?

On another note the define state is my favourite. Although maybe a few too many controls to move around. Also I’m not too sure where I should place some of the controllers. Do all of them matter? Are there more important control handles that I should be moving for example? Maybe some landmarks using some pictures that can help guide us through?

Now these are just thoughts and I love where it is but through I would ask some questions. 🤗

**Comment by jjburton** [comment]
@bgarnish 

- form state - proxy creation and aids on information used in rigging - thickness of lips, structure, and more
- The handles slide on the surface with depth offsets and forward offsets for the control shapes.  A common issue with facial students is understanding why joint depth is important as well as control placement. This has that kinda built in.
- If you can think of a simpler route, I'm all ears for iteration. 
- Define state is meant to be the simplest to follow. What controls do you think are too many? Pretty much every point of data I use to generate the form data. All of those land marks are important and yes it needs to be gone over for the full class stuff.
