### ISSUE TITLE
cgmScene | testing 

### ISSUE THREAD

**Issue by jjburton** [jjburton/cgmTools#61]
### New animation isn't updating variation section
Resulting in an error when you press Save New Version

**Comment by jjburton** [comment]
**Error when changing from character to props**

# Traceback (most recent call last):
#   File "D:\repos\cgmtools\mayaTools\cgm\core\mrs\Scene.py", line 716, in SetCategory
#     self.SaveOptions()
#   File "D:\repos\cgmtools\mayaTools\cgm\core\mrs\Scene.py", line 156, in SaveOptions
#     self.showBaked = self.showBakedOption( q=True, checkBox=True )
# TypeError: 'NoneType' object is not callable #

**Comment by benngarnish** [comment]
Scene is working!
