### ISSUE TITLE
new asset error

### ISSUE THREAD

**Issue by benngarnish** [jjburton/cgmTools#63]
`# Error: WindowsError: file C:/Users/benng/Documents/maya/scripts\cgm\core\mrs\Scene.py line 984: 3`

**Comment by dbokser** [comment]
is it giving any more info than that? The line is attempting to make a directory, so maybe it's a permission issue?

**Comment by bgarnish** [comment]
Hey. 
We don’t have any permissions setting in our machines at work. 
I’m currently in mrsdev branch. 

I do remember having to change the way you make a directory. Instead of using os I had to use sys

I shall try again to get more information.

**Comment by benngarnish** [comment]
Looking into this and the line of code where it's I get the error it looks like the os.mkdir operation isn't working on my machine.
I've had to use **mc.sysFile** before to get it to work.
Any suggestions?

**Comment by benngarnish** [comment]
No longer an issues
