### ISSUE TITLE
ngSkin Tool 

### ISSUE THREAD

**Issue by Arexagon** [jjburton/cgmTools#73]
# Error: NameError: file C:/Users/Administrator/Documents/maya/2017/scripts\cgm\core\tools\lib\tool_calls.py line 79: global name 'log' is not defined # 
/// Enviornment Info ///----------------------------------------------------------------------------------------------------
-- Maya product : Maya 2017 
-- Maya operatingSystemVersion : Microsoft Windows 7 Ultimate Edition, 64-bit Windows 7 Service Pack 1 (Build 7601)
 
-- Maya apiVersion : 201700 
-- Maya buildDirectory : ECS-564D6AE7:S:/Maya_2017_DI/build 
-- Maya application : maya 
-- Maya environmentFile : C:/Users/Administrator/Documents/maya/2017/Maya.env 
-- Maya version : 2017 
-- Maya file : 2017 
-- Maya date : 2016 06 15 03 45 
-- Maya cutIdentifier : 201606150345-997974 
-- Maya operatingSystem : win64

**Comment by jjburton** [comment]
@Arexagon | sorry mate. Just seeing this. what branch are you on and what tool were you trying to open?

**Comment by jjburton** [comment]
Attempted fix with MRSDEV commit  c881db7f4978df82f5216bef0d270d417908f871
