### ISSUE TITLE
Matt's Ideas and Issues...

### ISSUE THREAD

**Issue by jjburton** [jjburton/cgmTools#84]
Here you go, buddy:)

**Comment by mornst** [comment]
A setting for mirroring the animation with a time (frames) offset.

Example a 30 frame cycle would mirror with a 15 frame offset.  

![image](https://user-images.githubusercontent.com/4594909/78517882-4548aa80-7784-11ea-8564-22efe6caa1d9.png)

**Comment by jjburton** [comment]
Good idea. Keep em coming.

**Comment by mornst** [comment]
Would be awesome if there was direct rotational eye controls (placed directly over the eyes) that are nested under the lookat or an attribute that gives you the option to switch between lookat and direct. Honestly though I think they can co-exist at the same time and just use them as appropriate/needed.

**Comment by jjburton** [comment]
@mornst | there's fk eyes and direct eye controls.

On the eye settings

- Direct | turn on direct control and you should see a laser line coming out of the center of the eye.
- FK | turn on fk via the settings control and you'll see a laser line out of the eye with an an arrow on the end.

![image](https://user-images.githubusercontent.com/48218358/78988883-ba570f80-7af7-11ea-9e1c-883072239120.png)

**Comment by jjburton** [comment]
Also, not opposed to a hybrid overall, just haven't implemented.

**Comment by mornst** [comment]
ah, found em.   I think a hybrid ultimately would be a nice feature.  I've been known to animate my characters over all gaze with the lookat and animate the eye darts with the direct FK, get the best of both worlds.

**Comment by jjburton** [comment]
@mornst  | I'll add it to the list :)
