### ISSUE TITLE
mrs sphinx doc setup

### ISSUE THREAD

**Issue by jjburton** [jjburton/cgmTools#9]
Prep sphinx setup for MRS if possible to move that documentation to a better format than wordpress.

- [x] Can it be put behind the MRS membership
- [x] Setup system like for core sphinx
- [x] Hand off for content

**Comment by jjburton** [comment]
From R - first pass was unsuccessful. Trying again this weekend.

**Comment by jjburton** [comment]
Ryan has method. Josh, setup initial repos.

**Comment by jjburton** [comment]
@Comingdeer  - setup new private repos and did initial push. Do your magic.

**Comment by Comingdeer-FiveTalent** [comment]
thanks, on the schedule for tonight.
