### ISSUE TITLE
Marking Menu Issues

### ISSUE THREAD

**Issue by jjburton** [jjburton/cgmTools#96]
Working through optimization of the marking menu for May 2020 (up to Maya 2019.3)

**Comment by dbokser** [comment]
Marking menu sticks and doesnt exit upon release until I click somewhere else. Maya 2018.6

**Comment by jjburton** [comment]
Lots of fixes trying to address. 
Commit | 16dd98565e1391827f343eff91f97b3d2116241a

**Comment by liudger** [comment]
maya 2020 it's the same. 

A workaround is to release the mouse button directly and than the menu is still there and you can chose the action/menu and than the marking menu disappears. But this is not the normal marking menu behaviour:)

**Comment by jjburton** [comment]
Maya 2020 not actively supported. We've been looking to solutions on the marking menu front. I actually talked about it a it in this weeks rolling mrsDev post on our patreon. 

In short:

- dag menu's not ideal
- no custom hotbox ability at least as of my last dive into it in 2018's release
- Even with finickiness we use it all the time for the workflow
- All functions accessible via animate ui for puppet stuff or other menus.

https://www.patreon.com/mrsmakers

Looking for ideas on other solutions but coming up empty so far. It's much more responsive after the last fix and crashes from Maya 2017's handling of menu stuff seem to all be worked out.

**Comment by jjburton** [comment]
Also, the puppet menu get's faster as you work in a scene as it builds a buffer of contexts as you use it. Just FYI.
