### ISSUE TITLE
Bug DynParentTool

### ISSUE THREAD

**Issue by liudger** [jjburton/cgmTools#99]
`# Warning: cgm.core.tools.dynParentTool : object instance has no attribute : space`
when creating the setup the `space` attribute is not created on the control. When you add object to switch to this error pops up

maya 2020.1 windows

**Comment by liudger** [comment]
![afbeelding](https://user-images.githubusercontent.com/4112111/82458734-5c82f380-9ab7-11ea-82d6-3c2137875bb8.png)

**Comment by liudger** [comment]
It works when you add more object. But it should should also have it's original space

**Comment by jjburton** [comment]
- You need more than one space to build dynParent stuff(99% sure).
- It should build in place. 
- Maya 2020 isn't currently actively supported. Too many bugs.

Thanks for the report!

**Comment by jjburton** [comment]
2019.3 looking good though.

**Comment by jjburton** [comment]
http://docs.cgmonks.com/dynparenttool.html
